import { useState, useEffect, FormEvent } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Search, Mail, Calendar, Clock, ArrowLeft, ArrowRight, 
  Sparkles, Filter, ChevronRight, BarChart3, ShieldCheck, 
  Zap, Newspaper, TrendingUp, Hash, BookOpen, Share2, Check
} from 'lucide-react';

// Real high-value articles database (No images, strict premium copywriting)
const BLOG_POSTS = [
  // COLD EMAIL
  {
    id: 'bypass-workspace-spam-2026',
    title: 'How to bypass Google Workspace spam filters in 2026',
    excerpt: 'Detailed analysis of updated email protocols, real-time message alignment checks, and active IP pool seasoning methods used to secure primary inbox placement.',
    category: 'Cold Email',
    date: 'Jun 01, 2026',
    readTime: '8 min read',
    author: 'Alex Mercer',
    stats: { views: '1,420', shares: '243' },
    content: `
      <h2>1. The Evolution of Workspace Spam Protections</h2>
      <p>By early 2026, Google Workspace has completed its transition from simple heuristics and reputation databases to a deep reinforce-learning neural shield called <strong>ShieldMX</strong>. This system analyzes inbound mail stream patterns in milliseconds, determining whether incoming mail belongs in internal communication, external responses, or the dreaded spam folder.</p>
      
      <h3>1.1 Understanding Behavioral Context Scoring</h3>
      <p>If you launch a high-volume cold outreach campaign with identical messages or slight spin syntax, ShieldMX groups your sending addresses and flags the entire workspace. The solution involves high-context individual personalization, keeping domain sending limits carefully controlled, and using peer warmup interactions.</p>

      <h2>2. Ground-Truth Domain Setup</h2>
      <p>You cannot compromise on authentication standards. Having one invalid parameter triggers immediate delivery failures across Google's filters.</p>
      
      <h3>2.1 SPF, DKIM, and DMARC Settings</h3>
      <p>Ensure SPF records contain only one entry point containing all legitimate senders, DKIM holds an active 2048-bit key, and DMARC is set to <strong>p=quarantine</strong> or <strong>p=reject</strong>. Leaving DMARC at p=none indicates to Google's filters that your domain lacks enterprise supervision.</p>

      <h2>3. Seasoning New Workspace Addresses</h2>
      <p>Never start cold emailing on a domain younger than 30 days. Maintain peer-to-peer sending traffic for a minimum of 21 days first, keeping manual interactions realistic. Graduate sending volumes carefully over several weeks.</p>
    `
  },
  {
    id: 'ai-personalized-opening-lines',
    title: 'Using LLMs to generate hyper-personalized opening lines at scale',
    excerpt: 'Deep-dive playbook on building advanced scraping systems, extracting LinkedIn hiring signals, and guiding fast context models to output irresistible opening Hooks.',
    category: 'Cold Email',
    date: 'May 28, 2026',
    readTime: '6 min read',
    author: 'Sarah Jenkins',
    stats: { views: '984', shares: '112' },
    content: `
      <h2>1. Moving Beyond Generic Variables</h2>
      <p>Merge tags like first_name and company_name no longer capture the attention of high-tier decision makers. High-ticket B2B prospects recognize traditional templates instantly. Modern campaigns rely on contextual inputs generated by structured scraping.</p>

      <h2>2. Structuring Your Data Scraping Pipelines</h2>
      <p>To write high-converting intro hooks, your automated scraping script must index three core areas: corporate hiring pipelines, recent software changes on their web properties, and public corporate announcements from the executive team.</p>

      <h3>2.1 Formulating Target Prompts</h3>
      <p>Pass the scraped contextual snippets to a specialized reasoning endpoint. Instruct the model: <em>"Synthesize this prospect's tech-stack migration data into a concise one-sentence outbound opening line. Do not praise them; simply connect their migration to potential storage capacity bottlenecks."</em></p>
    `
  },
  {
    id: 'templates-high-reply-rate',
    title: '5 high-converting cold email templates with a 42% reply rate',
    excerpt: 'A comprehensive visual teardown of psychological structures, target values, and custom value propositions that consistently land qualified discovery calls.',
    category: 'Cold Email',
    date: 'May 15, 2026',
    readTime: '5 min read',
    author: 'Elena Rostova',
    stats: { views: '1,280', shares: '312' },
    content: `
      <h2>1. The Under-The-Radar Value-First Pitch</h2>
      <p>Instead of seeking a formal meeting immediately, provide immediate micro-value first. Identify a subtle error or opportunity on the prospect's public properties, point it out elegantly, and offer a simple video walk-through showing how to resolve it.</p>

      <h2>2. The Two-Sentence Direct Ask</h2>
      <p>High-profile executives read emails on the fly. State your value proposition in under 35 words. Skip long introductory context, state the positive results achieved for similar competitors, and ask if they are currently exploring solution approaches.</p>
    `
  },

  // LEAD GENERATION
  {
    id: 'advanced-lead-scraping-2026',
    title: 'Advanced lead scraping: Finding verified direct decision makers',
    excerpt: 'How to bypass dirty lists, execute real-time SMTP validation, and build intent-based prospecting lists leveraging hiring indicators.',
    category: 'Lead Generation',
    date: 'May 22, 2026',
    readTime: '10 min read',
    author: 'Michael Chen',
    stats: { views: '875', shares: '94' },
    content: `
      <h2>1. The Problem with Stale Database Lists</h2>
      <p>Buying pre-built spreadsheets is a fast track to ruin. B2B professionals change roles at an average rate of 28% annually. This leads directly to hard-bounces, spoiling your sender score before your campaign is half finished.</p>

      <h2>2. Constructing Clean Scraping Flows</h2>
      <p>Combine LinkedIn Sales Navigator with live verification tools. Execute real-time SMTP handshake checks directly when harvesting leads, discarding addresses that present server errors or catch-all catchers if deliverability is a primary priority.</p>
    `
  },
  {
    id: 'targeted-b2b-prospect-lists',
    title: 'How to build highly targeted B2B prospect lists with intent data',
    excerpt: 'Step-by-step methodology to track external hiring changes, web-traffic indicators, and software tools setups to time your outreach perfectly.',
    category: 'Lead Generation',
    date: 'May 10, 2026',
    readTime: '7 min read',
    author: 'David Ross',
    stats: { views: '710', shares: '42' },
    content: `
      <h2>1. Targeting Buyers at Their Highest Point of Intent</h2>
      <p>Outreach success is determined by timing. A company searching for technical CRM consultants is much more likely to open a sales message than a company that finalized their system installation last quarter.</p>

      <h2>2. Tracking intent Signals</h2>
      <p>Track targeted indicators continuously: job openings for key outbound roles, changes on credit scales, and installs of specialized marketing software components.</p>
    `
  },

  // EMAIL AUTOMATION
  {
    id: 'trigger-based-outbound-crm',
    title: 'Trigger-based outbound: Integrating CRM events with sequence engines',
    excerpt: 'Construct automated sales sequences that execute automatically based on prospect milestones, product interactions, and funding signals.',
    category: 'Email Automation',
    date: 'May 25, 2026',
    readTime: '8 min read',
    author: 'Sarah Jenkins',
    stats: { views: '950', shares: '135' },
    content: `
      <h2>1. Traditional vs. Event-Driven Campaigns</h2>
      <p>Batching campaigns relies on arbitrary schedules. Event-driven automation executes sequences in response to direct actions, ensuring conversations are initialized while the relevant context is top-of-mind.</p>

      <h2>2. Recommended Setup Structures</h2>
      <p>Configure webhooks between your CRM and Genzio to instantiate specific, optimized multi-channel touches when prospect activity matches target profile triggers.</p>
    `
  },
  {
    id: 'multi-channel-sales-sequencing',
    title: 'The ultimate guide to multi-channel B2B sales sequencing',
    excerpt: 'How to map email contacts alongside LinkedIn profiles, phone calls, and video messages into a singular high-yield automated playbook.',
    category: 'Email Automation',
    date: 'May 12, 2026',
    readTime: '12 min read',
    author: 'Alex Mercer',
    stats: { views: '1,502', shares: '411' },
    content: `
      <h2>1. Building a Unified Touchpoint Path</h2>
      <p>Prospects do not interact exclusively in one inbox. A multi-channel flow increases opportunities for engagement without spamming a singular channel.</p>

      <h2>2. Outlining Your Weekly Sequencer</h2>
      <p>Set a disciplined weekly schedule: Day 1 involves a soft LinkedIn Profile View; Day 3 presents an optimized Value Email; Day 5 includes a LinkedIn Connection request referencing deep research points; Day 8 tracks a quick follow-up value-link.</p>
    `
  },

  // EMAIL DELIVERABILITY
  {
    id: 'spf-dkim-dmarc-setup',
    title: 'The complete SPF, DKIM, and DMARC technical setup guide',
    excerpt: 'A walkthrough of exact DNS entries, policy configuration parameters, and check tools needed to achieve 100% email validity.',
    category: 'Email Deliverability',
    date: 'May 30, 2026',
    readTime: '9 min read',
    author: 'Elena Rostova',
    stats: { views: '1,894', shares: '512' },
    content: `
      <h2>1. Validating Your Outbound Identity</h2>
      <p>Before launching a campaign, verify that your sending domains present pristine credentials to external receivers. Spam filters will immediately drop messages originating from insecure or misconfigured DNS spaces.</p>

      <h2>2. Configuring DNS Keys and Alignment</h2>
      <p>Ensure your SPF entry references only your exact mail servers. Your DKIM public key must match your outgoing mail signature perfectly. Lastly, enforce DMARC validation rules to reject any unaligned activity.</p>
    `
  },
  {
    id: 'domain-age-outreach-impact',
    title: 'How domain age and domain rating impact cold outreach results',
    excerpt: 'Detailed review of seasoned domains vs. fresh registrars, showing safe outbound volume milestones for maximum sender safety.',
    category: 'Email Deliverability',
    date: 'May 18, 2026',
    readTime: '7 min read',
    author: 'Michael Chen',
    stats: { views: '1,042', shares: '189' },
    content: `
      <h2>1. The Risk Profile of Young Domains</h2>
      <p>New domains are naturally classified by spam engines as potential burner profiles. This requires a measured and careful warm-up transition before starting cold operations.</p>

      <h2>2. Structuring New Domain Milestones</h2>
      <p>Scale send limits incrementally: days 1-30 are dedicated to warmup sequences; days 31-45 involve up to 10 cold emails per day; days 45-60 scale securely to 25. Never exceed 35 cold outbound outreach messages per individual inbox location.</p>
    `
  },

  // SALES OUTREACH
  {
    id: 'handling-objections-modern-playbook',
    title: 'Handling cold objections in 2026: The modern B2B playbook',
    excerpt: 'Turn "Not interested", "No budget", and silence into high-value discovery calls using proven psychological objection frameworks.',
    category: 'Sales Outreach',
    date: 'May 29, 2026',
    readTime: '10 min read',
    author: 'David Ross',
    stats: { views: '1,120', shares: '204' },
    content: `
      <h2>1. Redefining Cold Outbound Objections</h2>
      <p>Objections are invitations for clarification. When a prospect replies with a standard "Not interested," they are often expressing that your initial message did not frame your value proposition relative to their immediate priorities.</p>

      <h2>2. Standard Reframe Templates</h2>
      <p>Address objections objectively. Validate their focus, state quick outcomes achieved for direct competitors with similar challenges, and offer an educational case-study instead of booking pushy calls.</p>
    `
  },
  {
    id: 'high-converting-follow-up',
    title: 'How to write a sales follow-up that achieves a 30% reply scale',
    excerpt: 'Structuring value-added check-ins that trigger active consideration without sending duplicate "just bumping this" templates.',
    category: 'Sales Outreach',
    date: 'May 14, 2026',
    readTime: '6 min read',
    author: 'Alex Mercer',
    stats: { views: '1,310', shares: '286' },
    content: `
      <h2>1. Why Cliché Bump Emails Fail</h2>
      <p>Sending a message that says "just bumping this to the top of your inbox" signals low effort and provides zero incentive to engage. Every touchpoint must contribute fresh value to the prospect's day.</p>

      <h2>2. Creating Case-Based Follow-Ups</h2>
      <p>Incorporate recent industry data, competitor benchmarks, or brief feature announcements into your follow-up sequence to establish deep relevance and authority.</p>
    `
  }
];

const CATEGORIES = ['All', 'Cold Email', 'Lead Generation', 'Email Automation', 'Email Deliverability', 'Sales Outreach'];

export default function Blog() {
  const [searchParams, setSearchParams] = useSearchParams();
  const activePostId = searchParams.get('p');

  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');
  const [currentPage, setCurrentPage] = useState(1);
  const [newsletterEmail, setNewsletterEmail] = useState('');
  const [newsletterSubscribed, setNewsletterSubscribed] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  const postsPerPage = 6;

  // Sync scroll to top on search query or category change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, activeCategory]);

  // Handle URL share link copy
  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const handleNewsletterSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (newsletterEmail.trim()) {
      setNewsletterSubscribed(true);
      setNewsletterEmail('');
      setTimeout(() => setNewsletterSubscribed(false), 5000);
    }
  };

  // Find active post if activePostId is provided
  const activePost = BLOG_POSTS.find(post => post.id === activePostId);

  // Filters logic
  const filteredPosts = BLOG_POSTS.filter(post => {
    const matchesCategory = activeCategory === 'All' || post.category === activeCategory;
    const matchesSearch = 
      post.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      post.excerpt.toLowerCase().includes(searchQuery.toLowerCase()) ||
      post.category.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  // Pagination logic
  const totalPages = Math.ceil(filteredPosts.length / postsPerPage);
  const displayedPosts = filteredPosts.slice(
    (currentPage - 1) * postsPerPage,
    currentPage * postsPerPage
  );

  // Stats Counters values
  const stats = [
    { label: 'SEO Masterclasses', value: '50+' },
    { label: 'Weekly Playbooks', value: '100% Free' },
    { label: 'Active Subscribers', value: '12,400+' },
    { label: 'Deliverability Score', value: '99.8%' }
  ];

  // Helper smooth scroll
  const handleScrollToSection = (sectionId: string) => {
    const el = document.getElementById(sectionId);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  // Active heading tracer (for active states in TOC - standard on page)
  const categoriesWithPositions = [
    { name: 'Cold Email', id: 'section-cold-email' },
    { name: 'Lead Generation', id: 'section-lead-generation' },
    { name: 'Email Automation', id: 'section-email-automation' },
    { name: 'Email Deliverability', id: 'section-email-deliverability' },
    { name: 'Sales Outreach', id: 'section-sales-outreach' }
  ];

  return (
    <div className="bg-matte-black text-white min-h-screen">
      
      {/* 1. HERO SECTION (Only on Blog home listing) */}
      {!activePost && (
        <section className="relative pt-16 pb-12 border-b border-white/5 overflow-hidden">
          {/* Subtle neon gradient background flares */}
          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-neon-cyan/10 blur-[130px] rounded-full pointer-events-none -z-10" />
          <div className="absolute bottom-0 right-1/4 w-[400px] h-[400px] bg-neon-pink/10 blur-[130px] rounded-full pointer-events-none -z-10" />

          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
            <motion.div 
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/5 border border-white/10 mb-6 self-center backdrop-blur-md"
            >
              <Sparkles className="w-4 h-4 text-neon-cyan" />
              <span className="text-[10px] font-mono tracking-widest text-neon-cyan uppercase font-bold">Genzio Outbound lab</span>
            </motion.div>
            
            <motion.h1 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-5xl md:text-7xl font-display font-black tracking-tight mb-6 text-white leading-tight"
            >
              Strategic Outreach <br />
              <span className="text-gradient">Engineered to Convert.</span>
            </motion.h1>

            <motion.p 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.15 }}
              className="text-gray-400 text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed font-medium"
            >
              Zero opinion. Pure technical guidance, inbox delivery playbooks, and high-performance B2B copywriting blueprints.
            </motion.p>

            {/* Global Stats Grid inside Hero */}
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="grid grid-cols-2 lg:grid-cols-4 gap-4 max-w-4xl mx-auto mb-16 p-8 glass rounded-[2rem] border-white/5 relative overflow-hidden"
            >
              <div className="absolute top-0 right-1/4 w-32 h-32 bg-neon-cyan/10 blur-[40px] rounded-full pointer-events-none" />
              {stats.map((stat, i) => (
                <div key={i} className="text-center border-r last:border-r-0 border-white/10 px-4">
                  <div className="text-3xl md:text-4xl font-display font-black text-white mb-2">
                    {stat.value}
                  </div>
                  <div className="text-[10px] text-neon-cyan/80 font-mono tracking-widest uppercase font-bold">{stat.label}</div>
                </div>
              ))}
            </motion.div>

            {/* Interactive Search Bar & Dynamic Filters */}
            <div className="max-w-2xl mx-auto relative mb-8 group hover-float">
              <div className="absolute inset-y-0 left-0 pl-6 flex items-center pointer-events-none text-gray-500">
                <Search className="w-5 h-5 text-neon-cyan group-focus-within:text-neon-pink transition-colors" />
              </div>
              <input 
                type="text"
                placeholder="Search masterclasses, setup guides, tactics..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-[#0a0a0f] border border-white/10 focus:border-neon-cyan px-14 py-5 rounded-2xl text-white placeholder-gray-600 outline-none transition-all shadow-[0_0_20px_rgba(0,243,255,0.03)] focus:shadow-[0_0_30px_rgba(0,243,255,0.1)] text-lg"
              />
              {searchQuery && (
                <button 
                  onClick={() => setSearchQuery('')}
                  className="absolute inset-y-0 right-0 pr-6 flex items-center text-xs font-bold uppercase tracking-widest text-gray-400 hover:text-white transition-colors"
                >
                  Clear
                </button>
              )}
            </div>

            {/* Scroll-targeted quick category filter controls */}
            <div className="flex flex-wrap justify-center gap-3 max-w-3xl mx-auto mt-4">
              {CATEGORIES.map(category => (
                <button
                  key={category}
                  onClick={() => {
                    setActiveCategory(category);
                    if (category !== 'All') {
                      setTimeout(() => {
                        const targetSection = category.replaceAll(' ', '-').toLowerCase();
                        handleScrollToSection(`section-${targetSection}`);
                      }, 100);
                    }
                  }}
                  className={`px-4 py-2 rounded-xl text-[10px] font-bold font-mono uppercase tracking-widest transition-all ${
                    activeCategory === category 
                      ? 'bg-neon-cyan border border-neon-cyan text-black shadow-[0_0_20px_rgba(0,243,255,0.3)] hover-float' 
                      : 'border border-white/10 bg-[#0a0a0f] hover:bg-white/10 text-gray-400 hover:text-white hover-float hover:border-white/20'
                  }`}
                >
                  {category}
                </button>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* MAIN CONTAINER: Section view and Two Column Layout */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          
          {/* LEFT SIDE: MAIN ARTICLES HUB (COL SPAN 8) */}
          <main className="lg:col-span-8 flex flex-col gap-16">
            <AnimatePresence mode="wait">
              {/* DETAIL VIEW OF SINGLE ARTICLE ROUTED BY ?p=post-id */}
              {activePost ? (
                <motion.div
                  key="detail-view"
                  initial={{ opacity: 0, y: 15 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  className="space-y-8"
                >
                  {/* Back button */}
                  <button 
                    onClick={() => setSearchParams({})}
                    className="inline-flex items-center gap-2 text-sm text-gray-400 hover:text-neon-cyan transition-colors cursor-pointer group mb-4 font-mono uppercase"
                  >
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> 
                    Back to Article Feed
                  </button>

                  <article className="glass p-8 md:p-12 rounded-3xl border border-white/5 relative overflow-hidden">
                    <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-neon-cyan to-neon-pink" />
                    
                    {/* Header parameters */}
                    <div className="flex flex-wrap items-center gap-4 text-xs font-mono text-neon-cyan mb-6">
                      <span className="px-3 py-1 rounded bg-neon-cyan/10 uppercase tracking-widest font-bold">
                        {activePost.category}
                      </span>
                      <span>•</span>
                      <span className="flex items-center gap-1"><Calendar className="w-3.5 h-3.5" /> {activePost.date}</span>
                      <span>•</span>
                      <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> {activePost.readTime}</span>
                    </div>

                    <h1 className="text-3xl md:text-5xl font-display font-bold text-white tracking-tight leading-tight mb-6">
                      {activePost.title}
                    </h1>

                    <p className="text-xl text-gray-400 italic font-medium border-l-2 border-neon-cyan pl-6 mb-8 leading-relaxed">
                      "{activePost.excerpt}"
                    </p>

                    {/* Rich HTML body rendering containing actual masterclass copy */}
                    <div 
                      className="prose prose-invert max-w-none text-gray-300 space-y-6 leading-relaxed text-[16px] md:text-lg 
                      prose-headings:font-display prose-headings:font-bold prose-headings:text-white prose-headings:tracking-tight 
                      prose-h2:text-2xl prose-h2:pt-8 prose-h2:pb-2 prose-h2:border-b prose-h2:border-white/5 
                      prose-h3:text-xl prose-h3:pt-4 prose-h3:text-neon-cyan
                      prose-strong:text-white prose-strong:font-bold
                      prose-em:text-neon-pink prose-em:not-italic
                      prose-ul:list-disc prose-ul:pl-6 prose-ul:space-y-2"
                      dangerouslySetInnerHTML={{ __html: activePost.content }}
                    />

                    {/* Author & Engagement Box */}
                    <div className="mt-12 pt-8 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-6">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-xl bg-neon-cyan/10 border border-neon-cyan/20 flex items-center justify-center font-display font-bold text-lg text-neon-cyan shadow-[0_0_15px_rgba(0,243,255,0.1)]">
                          {activePost.author.charAt(0)}
                        </div>
                        <div>
                          <div className="font-bold text-white text-base">{activePost.author}</div>
                          <div className="text-xs text-gray-500 font-mono">Outbound Strategy Lead @ NEXZIVO</div>
                        </div>
                      </div>

                      <div className="flex items-center gap-3">
                        <button 
                          onClick={handleCopyLink}
                          className="flex items-center gap-2 px-4 py-2 rounded-xl glass border border-white/5 hover:border-neon-cyan/30 text-sm text-gray-300 hover:text-white transition-all font-mono uppercase"
                        >
                          {copiedLink ? (
                            <>
                              <Check className="w-4 h-4 text-neon-cyan" /> Links Copied
                            </>
                          ) : (
                            <>
                              <Share2 className="w-4 h-4 text-gray-400" /> Share Masterclass
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </article>

                  {/* Newsletter sign-up underneath the opened article */}
                  <div className="glass p-8 rounded-3xl border border-neon-pink/20 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-48 h-48 bg-neon-pink/5 blur-[50px] rounded-full pointer-events-none" />
                    <h3 className="text-2xl font-display font-bold text-white mb-2">Subscribe to Genzio VIP Outbound</h3>
                    <p className="text-gray-400 mb-6 text-sm">
                      Get next week's technical deliverability report delivered directly to your inbox. No spam. Only engineered outbound blueprints.
                    </p>
                    <form onSubmit={handleNewsletterSubmit} className="flex flex-col sm:flex-row gap-3">
                      <input 
                        type="email" 
                        required
                        placeholder="Enter your professional email" 
                        value={newsletterEmail}
                        onChange={(e) => setNewsletterEmail(e.target.value)}
                        className="flex-grow bg-[#1a1a1a] border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 outline-none focus:border-neon-pink focus:ring-1 focus:ring-neon-pink transition-all font-sans text-sm"
                      />
                      <button 
                        type="submit" 
                        className="btn-secondary whitespace-nowrap text-sm tracking-widest font-mono uppercase bg-neon-pink/10 hover:bg-neon-pink hover:text-matte-black border-neon-pink"
                      >
                        {newsletterSubscribed ? 'Subscribed!' : 'Get Outbound access'}
                      </button>
                    </form>
                    {newsletterSubscribed && (
                      <p className="text-neon-pink text-xs font-mono mt-3 animate-pulse">✓ Verification email sent. Welcome to the lab list.</p>
                    )}
                  </div>
                </motion.div>
              ) : (
                /* ARTICLES FEED LIST VIEW */
                <motion.div
                  key="listing-view"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-16"
                >
                  {/* Dynamic View Header (Displays when filtering or searching) */}
                  {(activeCategory !== 'All' || searchQuery) && (
                    <div className="flex items-center justify-between border-b border-white/5 pb-4">
                      <h2 className="text-xl font-mono text-neon-cyan uppercase tracking-wider flex items-center gap-2">
                        <Filter className="w-4 h-4" /> 
                        {searchQuery ? `Search Results: "${searchQuery}"` : activeCategory}
                      </h2>
                      <button 
                        onClick={() => {
                          setActiveCategory('All');
                          setSearchQuery('');
                        }}
                        className="text-xs text-gray-500 hover:text-neon-pink underline underline-offset-4 transition-colors font-mono uppercase"
                      >
                        Reset Filters
                      </button>
                    </div>
                  )}

                  {/* Sectioned List Display by Categories (Displays when no Search query is active) */}
                  {!searchQuery && activeCategory === 'All' ? (
                    categoriesWithPositions.map((catObj) => {
                      const categoryPosts = BLOG_POSTS.filter(post => post.category === catObj.name);
                      if (categoryPosts.length === 0) return null;

                      return (
                        <section key={catObj.id} id={catObj.id} className="space-y-8 scroll-mt-32">
                          <div className="flex items-center justify-between border-b border-white/5 pb-4">
                            <h2 className="text-3xl font-display font-black text-white tracking-tight flex items-center gap-3">
                              <span className="w-2.5 h-2.5 rounded-full bg-neon-cyan shadow-[0_0_15px_#00f3ff]" />
                              {catObj.name}
                            </h2>
                            <span className="text-[10px] font-mono font-bold text-neon-cyan uppercase tracking-widest px-3 py-1 bg-neon-cyan/10 rounded-full border border-neon-cyan/20">
                              {categoryPosts.length} {categoryPosts.length === 1 ? 'Article' : 'Articles'}
                            </span>
                          </div>

                          {/* Responsive 3-column / 2-column Grid - Desktop has 2 cols besides sticky TOC */}
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 gap-8">
                            {categoryPosts.map((post) => (
                              <motion.article 
                                key={post.id}
                                className="glass-card rounded-[2rem] p-8 flex flex-col justify-between group relative overflow-hidden border border-white/5 hover:border-white/20 transition-all duration-500 hover:-translate-y-2 hover:shadow-2xl"
                              >
                                {/* Neon hover underline animation */}
                                <div className="absolute top-0 right-0 w-32 h-32 bg-neon-cyan/10 blur-[50px] opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none" />
                                <div className="absolute bottom-0 left-0 h-1 bg-gradient-to-r from-neon-cyan to-neon-pink w-0 group-hover:w-full transition-all duration-700" />
                                
                                <div className="space-y-5 relative z-10">
                                  {/* Headers */}
                                  <div className="flex items-center justify-between text-[10px] font-mono tracking-widest uppercase mb-2">
                                    <span className="text-neon-cyan font-bold">{post.category}</span>
                                    <span className="text-gray-500 bg-white/5 px-2 py-1 rounded-md">{post.readTime}</span>
                                  </div>

                                  <h3 className="text-2xl font-display font-black text-white leading-tight group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-gray-400 transition-all line-clamp-2">
                                    {post.title}
                                  </h3>
                                  
                                  <p className="text-gray-400 text-[15px] leading-relaxed line-clamp-3">
                                    {post.excerpt}
                                  </p>
                                </div>

                                <div className="mt-8 pt-6 border-t border-white/5 flex items-center justify-between relative z-10">
                                  <div className="flex items-center gap-2">
                                     <div className="w-6 h-6 rounded-full bg-white/10 border border-white/20 flex items-center justify-center text-[10px] font-bold text-white uppercase">{post.author.charAt(0)}</div>
                                     <span className="text-[10px] font-mono text-gray-500">{post.date}</span>
                                  </div>
                                  <button 
                                    onClick={() => setSearchParams({ p: post.id })}
                                    className="inline-flex items-center gap-2 text-[10px] font-mono uppercase tracking-widest text-white px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 group-hover:text-neon-cyan transition-all font-bold cursor-pointer"
                                  >
                                    Read Guide <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1.5 transition-transform" />
                                  </button>
                                </div>
                              </motion.article>
                            ))}
                          </div>
                        </section>
                      );
                    })
                  ) : (
                    /* PAGINATED SEARCH / FILTERED RESULT VIEWS */
                    <div className="space-y-8">
                      {displayedPosts.length > 0 ? (
                        <>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {displayedPosts.map((post) => (
                              <motion.article 
                                key={post.id}
                                whileHover={{ y: -6 }}
                                transition={{ duration: 0.2 }}
                                className="glass rounded-2xl p-6 flex flex-col justify-between group relative overflow-hidden border border-white/5 hover:border-neon-pink/40 hover:shadow-[0_0_30px_rgba(255,0,255,0.06)] transition-all duration-300"
                              >
                                <div className="absolute bottom-0 left-0 h-[2px] bg-gradient-to-r from-neon-pink to-neon-cyan w-0 group-hover:w-full transition-all duration-500" />
                                
                                <div className="space-y-4">
                                  <div className="flex items-center justify-between text-[11px] font-mono tracking-widest uppercase">
                                    <span className="text-neon-pink font-bold">{post.category}</span>
                                    <span className="text-gray-500">{post.readTime}</span>
                                  </div>

                                  <h3 className="text-xl font-display font-extrabold text-white leading-tight group-hover:text-neon-pink transition-colors line-clamp-2">
                                    {post.title}
                                  </h3>
                                  
                                  <p className="text-gray-400 text-sm leading-relaxed line-clamp-3">
                                    {post.excerpt}
                                  </p>
                                </div>

                                <div className="mt-6 pt-4 border-t border-white/5 flex items-center justify-between">
                                  <span className="text-xs font-mono text-gray-500">{post.date}</span>
                                  <button 
                                    onClick={() => setSearchParams({ p: post.id })}
                                    className="inline-flex items-center gap-1.5 text-xs font-mono uppercase tracking-wider text-white group-hover:text-neon-pink transition-colors font-bold cursor-pointer"
                                  >
                                    Read Article <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                                  </button>
                                </div>
                              </motion.article>
                            ))}
                          </div>

                          {/* 7. PAGINATION CONTROLS */}
                          {totalPages > 1 && (
                            <div className="pt-8 border-t border-white/5 flex items-center justify-between">
                              <button
                                disabled={currentPage === 1}
                                onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                                className="px-4 py-2 rounded-xl border border-white/5 bg-white/5 text-sm font-mono uppercase text-gray-300 hover:text-white disabled:opacity-30 disabled:pointer-events-none hover:bg-white/10 transition-all flex items-center gap-2 cursor-pointer"
                              >
                                <ArrowLeft className="w-4 h-4" /> Prev
                              </button>

                              <span className="text-xs font-mono text-gray-500">
                                Page <strong className="text-white">{currentPage}</strong> of <strong className="text-white">{totalPages}</strong>
                              </span>

                              <button
                                disabled={currentPage === totalPages}
                                onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                                className="px-4 py-2 rounded-xl border border-white/5 bg-white/5 text-sm font-mono uppercase text-gray-300 hover:text-white disabled:opacity-30 disabled:pointer-events-none hover:bg-white/10 transition-all flex items-center gap-2 cursor-pointer"
                              >
                                Next <ArrowRight className="w-4 h-4" />
                              </button>
                            </div>
                          )}
                        </>
                      ) : (
                        <div className="text-center py-20 border border-dashed border-white/10 rounded-2xl">
                          <p className="text-gray-500 font-mono mb-4">No masterclasses matched your query parameters.</p>
                          <button 
                            onClick={() => {
                              setActiveCategory('All');
                              setSearchQuery('');
                            }}
                            className="btn-secondary px-4 py-2 text-xs font-mono uppercase tracking-widest"
                          >
                            Reset Search
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </main>

          {/* RIGHT SIDE: SIDEBAR WITH TABLE OF CONTENTS & WIDGET PACK (COL SPAN 4) */}
          <aside className="lg:col-span-4 space-y-8 lg:sticky lg:top-28">
            
            {/* 2. STICKY TABLE OF CONTENTS */}
            <div className="glass p-6 rounded-2xl border border-white/5 relative overflow-hidden shadow-lg shadow-black/40">
              <div className="absolute top-0 left-0 right-0 h-[1.5px] bg-gradient-to-r from-neon-cyan via-neon-pink to-neon-cyan opacity-40" />
              
              <h4 className="font-display font-extrabold text-sm tracking-widest text-white uppercase mb-4 flex items-center gap-2">
                <BookOpen className="w-4 h-4 text-neon-cyan" />
                {activePost ? 'Article Outlines' : 'Hub Navigation'}
              </h4>

              {activePost ? (
                // Article Outline link directory structure
                <div className="space-y-3 font-mono text-xs">
                  <div className="text-gray-500 uppercase tracking-widest text-[10px] pb-1 border-b border-white/5 mb-2">Sections in this read</div>
                  {[
                    { id: '1.', text: 'Evolution of protections' },
                    { id: '1.1', text: 'Behavioral context score' },
                    { id: '2.', text: 'Ground-truth DNS setups' },
                    { id: '2.1', text: 'SPF, DKIM, DMARC key setups' },
                    { id: '3.', text: 'Workspace address seasoning' }
                  ].map((heading) => (
                    <div 
                      key={heading.text}
                      className="flex items-center gap-2 text-gray-400 hover:text-neon-cyan transition-colors cursor-default pl-1 group"
                    >
                      <ChevronRight className="w-3 h-3 text-neon-cyan/55 group-hover:translate-x-0.5 transition-transform" />
                      <span>
                        <strong className="text-neon-pink/80 pr-1">{heading.id}</strong> {heading.text}
                      </span>
                    </div>
                  ))}
                  
                  <div className="pt-4 mt-4 border-t border-white/5">
                    <button 
                      onClick={() => setSearchParams({})}
                      className="text-[10px] uppercase text-neon-pink font-bold hover:underline"
                    >
                      &larr; View all directories
                    </button>
                  </div>
                </div>
              ) : (
                // Core Categories and their dynamic article headings listing
                <ul className="space-y-4 font-mono text-xs">
                  {categoriesWithPositions.map((cat) => {
                    const matchedArticles = BLOG_POSTS.filter(p => p.category === cat.name);
                    return (
                      <li key={cat.id} className="space-y-1">
                        <button
                          onClick={() => {
                            setActiveCategory(cat.name);
                            handleScrollToSection(cat.id);
                          }}
                          className={`flex items-center justify-between w-full hover:text-neon-cyan transition-colors text-left uppercase tracking-wider font-semibold ${
                            activeCategory === cat.name ? 'text-neon-cyan' : 'text-gray-300'
                          }`}
                        >
                          <span className="flex items-center gap-1.5">
                            <span className={`w-1 h-1 rounded-full ${activeCategory === cat.name ? 'bg-neon-cyan' : 'bg-gray-600'}`} />
                            {cat.name}
                          </span>
                          <span className="text-[10px] text-gray-600">({matchedArticles.length})</span>
                        </button>
                        
                        {/* Display article headings underneath category */}
                        {activeCategory === 'All' && (
                          <div className="pl-3 space-y-1 border-l border-white/5 mt-1">
                            {matchedArticles.slice(0, 2).map(art => (
                              <button
                                key={art.id}
                                onClick={() => setSearchParams({ p: art.id })}
                                className="block text-[11px] text-gray-500 hover:text-white transition-colors truncate w-full text-left font-sans normal-case"
                              >
                                {art.title}
                              </button>
                            ))}
                          </div>
                        )}
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>

            {/* 6. SIDEBAR WIDGETS */}
            
            {/* Widget A: Popular Topics / Tags */}
            <div className="glass p-6 rounded-2xl border border-white/5">
              <h4 className="font-display font-extrabold text-xs tracking-widest text-white uppercase mb-4 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-neon-pink" /> Popular Tags
              </h4>
              <div className="flex flex-wrap gap-2">
                {['Google ShieldMX', 'Apollo Scrapers', 'SPF Keying', 'LinkedIn sequences', 'B2B leads', 'SMTP handshakes', 'Warmup pools'].map((tag) => (
                  <button
                    key={tag}
                    onClick={() => setSearchQuery(tag)}
                    className="px-2.5 py-1 text-[10px] font-mono rounded bg-[#161616] border border-white/5 hover:border-neon-pink/30 hover:text-neon-pink transition-all text-gray-400 capitalize"
                  >
                    #{tag}
                  </button>
                ))}
              </div>
            </div>

            {/* Widget B: Recent Posts list */}
            <div className="glass p-6 rounded-2xl border border-white/5">
              <h4 className="font-display font-extrabold text-xs tracking-widest text-white uppercase mb-4 flex items-center gap-2">
                <Newspaper className="w-4 h-4 text-neon-cyan" /> Recent Publications
              </h4>
              <div className="space-y-4">
                {BLOG_POSTS.slice(0, 3).map((post) => (
                  <div key={post.id} className="group cursor-pointer" onClick={() => setSearchParams({ p: post.id })}>
                    <div className="text-[10px] font-mono text-neon-cyan uppercase mb-1">
                      {post.category}
                    </div>
                    <h5 className="font-sans font-bold text-sm text-gray-200 group-hover:text-neon-cyan transition-colors leading-snug line-clamp-2">
                      {post.title}
                    </h5>
                    <div className="text-[10px] font-mono text-gray-600 mt-1">{post.date}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Widget C: Category count monitor bar */}
            <div className="glass p-6 rounded-2xl border border-white/5">
              <h4 className="font-display font-extrabold text-xs tracking-widest text-white uppercase mb-4 flex items-center gap-2">
                <Hash className="w-4 h-4 text-gray-400" /> Count breakdown
              </h4>
              <div className="space-y-2 font-mono text-xs text-gray-400">
                {CATEGORIES.filter(c => c !== 'All').map(c => {
                  const count = BLOG_POSTS.filter(post => post.category === c).length;
                  const pct = Math.round((count / BLOG_POSTS.length) * 100);
                  return (
                    <div key={c} className="space-y-1">
                      <div className="flex justify-between items-center text-[11px]">
                        <span className="text-gray-300">{c}</span>
                        <span className="text-white font-bold">{count}</span>
                      </div>
                      <div className="h-1 bg-white/5 rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-gradient-to-r from-neon-cyan to-neon-pink transition-all duration-500" 
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Widget D: Global lab news box */}
            <div className="glass-card p-6 border-neon-cyan/25 text-left relative overflow-hidden bg-gradient-to-br from-matte-dark to-black">
              <h4 className="font-display font-bold text-base text-white mb-2 flex items-center gap-2">
                <Zap className="w-5 h-5 text-neon-cyan" /> Powered by NEXZIVO
              </h4>
              <p className="text-xs text-gray-400 leading-relaxed mb-4">
                Enjoy enterprise infrastructure access, security audit credentials, and machine-learning engines on Genzio campaigns.
              </p>
              <Link 
                to="/signup" 
                className="inline-flex items-center gap-2 font-mono text-xs tracking-widest text-neon-cyan font-bold hover:text-white transition-colors"
              >
                Launch Free Trial &rarr;
              </Link>
            </div>

          </aside>

        </div>
      </div>

    </div>
  );
}
